config/routes.rb
Charmbuy::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :messages

  resources :users

  resources :shops

  resources :news

  get "home/index"
  root :to => 'home#index'
  
  resources :docs

end

app/models/doc.rb
class Doc < ActiveRecord::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.json
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, :notice => 'Doc was successfully created.' }
        format.json { render :json => @doc, :status => :created, :location => @doc }
      else
        format.html { render :action => "new" }
        format.json { render :json => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.json
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to @doc, :notice => 'Doc was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Listing docs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docs.each do |doc| %>
  <tr>
    <td><%= doc.title %></td>
    <td><%= doc.body %></td>
    <td><%= link_to 'Show', doc %></td>
    <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
    <td><%= link_to 'Destroy', doc, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @doc.title %>
</p>

<p>
  <b>Body:</b>
  <%= @doc.body %>
</p>


<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>